#ifndef State_h
#define State_h

typedef enum  {
    DISPLAY_VOLUME,
    DISPLAY_TIME,
    SET_HOURS,
    SET_MINUTES,
    DISPLAY_DATE,
    SET_YEAR,
    SET_MONTH,
    SET_DAY,
    DISPLAY_ALARM_1,
    SET_ENABLED_1,
    SET_HOURS_1,
    SET_MINUTES_1,
    SET_WEEKEND_1,
    SET_TRACK_1,
    DISPLAY_ALARM_2,
    SET_ENABLED_2,
    SET_HOURS_2,
    SET_MINUTES_2,
    SET_WEEKEND_2,
    SET_TRACK_2,
    RINGING_ALARM_1,
    RINGING_ALARM_2,
    RINGING_NAP,
    DISPLAY_NAP_INTRO,
    SET_NAP,
    DISPLAY_NAP,
    DARK_MODE
} State;

#endif
